<%@ taglib prefix="s" uri="/struts-tags" %>
<%  response.setHeader("Expires", "0");response.setHeader("Cache-Control", "must-revalidate, post-check=0, pre-check=0");response.setHeader("Pragma", "public");
response.setHeader("Content-Disposition","inline; filename=waivers.csv");response.setContentType("application/csv"); %>Waiver Number,Entity,Service Address,Status,Date,Expire Date,Signed Date,Recorder Date,Deed Instrument #,Parcel PIN,Parcel Tax ID,Legal Description,Township Section Range,Lot,Acreage,Develop/Subdiv,In/Out City,Waiver Notes,GIS Notes,Mapped Date
<s:iterator var="one" value="waivers"><s:property value="waiverNum" />,"<s:property value="entitiesInfo" />","<s:property value="addressInfo" />",<s:property value="status" />,<s:property value="date" />,<s:property value="expireDate" />,<s:property value="signedDate" />,<s:property value="recorderDate" />,<s:property value="deedInstrumentNum" />,"<s:property value="parcelPin" />","<s:property value="parcelTaxId" />","<s:property value="legalDescription" />","<s:property value="secTwpRangeDir" />","<s:property value="lot" />","<s:property value="acreage" />",<s:property value="developmentSubdivision" />",<s:property value="inOutCity" />,"<s:property value="notes" />","<s:property value="gisNotes" />","<s:property value="mappedDate" />"
</s:iterator>























































