<%@ taglib prefix="s" uri="/struts-tags" %>
<%  response.setHeader("Expires", "0");response.setHeader("Cache-Control", "must-revalidate, post-check=0, pre-check=0");response.setHeader("Pragma", "public");
response.setHeader("Content-Disposition","inline; filename=waivers.csv");response.setContentType("application/csv"); %>Waiver #,Waiver Instrum #,Deed Instrum #,Entity(ies),Legal Desc,Parcel Tax,Parcel Pin,Service Address,Township Sec/Range,Lot,Acreage,Develop/Subdiv,IN/OUT City,Date,Signed Date,Recorded Date,Mapped Date,Status\n
<s:iterator var="one" value="waivers"><s:property value="waiverNum" />,"<s:property value="waverInstrumentNum" />","<s:property value="deedInstrumentNum" />","<s:property value="entitiesInfo" />","<s:property value="legalDescription" />","<s:property value="parcelTaxId" />","<s:property value="parcelPin" />","<s:property value="addressInfo" />","<s:property value="secTwpRangeDir" />","<s:property value="lot" />","<s:property value="acreage" />","<s:property value="developmentSubdivision" />","<s:property value="inOutCity" />",<s:property value="date" />,<s:property value="signedDate" />,<s:property value="recorderDate" />,<s:property value="mappedDate" />,<s:property value="status" />
</s:iterator>























































